#build and deploy containers to GKE.
steps:
 # Step 0. build container image.
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "us-west1-docker.pkg.dev/$PROJECT_ID/wanna-b-gtc-repo/react-frontend", "-f", "react-frontend/Dockerfile", "."]

  # Step 1. push frontend iamge to AR.
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "us-west1-docker.pkg.dev/$PROJECT_ID/wanna-b-gtc-repo/react-frontend"]

  # Step 2. begin GKE work.
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=react-gke/
  - --location=us-west1
  - --cluster=zonar-zpeek-cluster-1

timeout: "1200s"
options:
  logging: CLOUD_LOGGING_ONLY
  