# .
apiVersion: v1
kind: Service
metadata:
  name: zpeek-react-service
  labels:
    app: react-frontend
spec:
  type: LoadBalancer
  selector:
    app: react-frontend
  ports:
  - port: 80
    targetPort: 8080